version: '2'
services:
  web:
    build: .
    #command: npm run develop
    volumes:
      - .:/usr/app/
      - ../sqlitedata:/sqlitedata
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: empiredb